name: imobilier
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1


  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.8
  mongo_dart: ^0.10.5
  image_picker: ^0.8.9
  flutter_launcher_icons: ^0.14.4
  geocoding: ^2.0.5
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/img1.jpg
    - assets/img2.jpg
    - assets/img3.jpg
    - assets/img4.jpg
    - assets/logo.png
